### PR TITLE
Remove obsolete :mock and :meck dependencies

### PR DESCRIPTION
**Pull request by kmakiela**
This PR removes `:meck` and `:mock` from the dependency list.
Both `:meck` and `:mock` are not needed anymore. All the tests that used these libraries were already rewritten (most of them use `:mox` now).

### CODE REVIEW

**Comment by NelsonVides** [comment]
So cool it would be so simple to get rid of Mock 😄 
But what about the `mix.lock` file, doesn't that one need to be cleaned out as well?

**Review by leszke — APPROVED** [review]

**Comment by michalwski** [comment]
@kmakiela I second @NelsonVides questions. Looks like mix.lock needs an update.

**Comment by kmakiela** [comment]
Further investigation shows that `:meck` is still loaded as a Sparrow dependency (and Sparrow only) so this PR is temporarily blocked by:
https://github.com/esl/sparrow/pull/47

**Comment by NelsonVides** [comment]
@kmakiela https://github.com/esl/sparrow/pull/47 was merged, we can move forward with this one 🙂

**Review by NelsonVides — APPROVED** [review]
Neat 🎉

**Pull request merged**
